### ISSUE TITLE
Deploy tangle.ee website

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/tangle.ee#1]
As discussed with Andrew Brough and Begoña Alvarez, our current plan is the following:

1. Host the source code here: https://github.com/EclipseFdn/tangle.ee
2. Begoña and Rihards will have commit access to the repository.
3. Use netlify.com as the hosting service. 

Timelines

1.  **January 23:** IOTA will push the source code to this repository. The should include a netlify.toml file with configurations similar to https://github.com/EclipseFdn/sparkplug.eclipse.org/blob/master/netlify.toml but with configurations for this application.

I would recommended creating a free account for testing the netlify.toml file. I would also recommend looking at the https://github.com/EclipseFdn/sparkplug.eclipse.org repository as an example for the following files that I expect to see in this repo:

https://github.com/EclipseFdn/sparkplug.eclipse.org/blob/master/CODE_OF_CONDUCT.md
https://github.com/EclipseFdn/sparkplug.eclipse.org/blob/master/CONTRIBUTING.md
https://github.com/EclipseFdn/sparkplug.eclipse.org/blob/master/LICENSE
https://github.com/EclipseFdn/sparkplug.eclipse.org/blob/master/NOTICE.md

2. **January 24:** Once this is done, Matt Ward and I will update the DNS for tangle.ee and point it to netlify.com

3. **January 24-January 27:** DNS propagation period

4. **January 28:** tangle.ee is live

**Comment by begonaalvarezd** [comment]
@chrisguindon Thank you very much for the detailed explanation.

Regarding the deployment, how is it planned to be organized? Every new push to the `master` branch creates automatically a new deployment in production? Or are the deployments manually triggered by your team?

**Comment by chrisguindon** [comment]
@begonaalvarezd Netlify will update the production website each time you push to master and the great thing about this service is that it will also generate a unique url each time someone creates a PR to allow everyone to review the website before the change is merged to master. 

An example from jakarta.ee:
https://github.com/jakartaee/jakarta.ee/pull/598

**Comment by chrisguindon** [comment]
It's important to note that a lot of this is somewhat configurable. 

I would recommend checking out the Netlify Docs: https://docs.netlify.com/configure-builds/common-configurations/

**Comment by chrisguindon** [comment]
@begonaalvarezd Is your team still planning to push the code + netlify configurations by the end of today?

This deadline is critical for making sure that we meet the January 28th deadline.

**Comment by begonaalvarezd** [comment]
@chrisguindon is being delayed until further notice.

**Comment by chrisguindon** [comment]
@begonaalvarezd thanks for the update!

**Comment by digital-zen** [comment]
@chrisguindon We are aiming for Friday to merge. Is this sufficient time from your perspective?

**Comment by chrisguindon** [comment]
@digital-zen It should be fine if the push is done before 11am EST! This will give me and @eclipsewebmaster a few hours to make the necessary changes to the domain before we leave for the week-end!

**Comment by begonaalvarezd** [comment]
@chrisguindon I just pushed the code into the `develop` branch for you to test a staging deployment. Please let me know if there is anything wrong or any file missing.

**Comment by chrisguindon** [comment]
@begonaalvarezd thanks! Can you rebase your branch? We were working in parallel so your branch is missing my last commit! 

I am currently testing netifly and your rebase should trigger a preview deployment of your branch so that we can test if all is well.

**Comment by begonaalvarezd** [comment]
@chrisguindon My branch already has a `netlify.toml` prepared for the website, which will conflict with yours. How should we proceed? Should I just merge and fix the conflict so my `netlify.toml` stays? 
Sorry for the trouble.

**Comment by chrisguindon** [comment]
@begonaalvarezd Mine is simply a temporary solution for hosting the coming soon page. Make sure that your version overwrites mine on your branch!

**Comment by begonaalvarezd** [comment]
@chrisguindon done, I just merged `master` into `develop` and fixed the conflict so my version stays. Anything else please let me know.

**Comment by chrisguindon** [comment]
@begonaalvarezd Thanks! Your change did trigger a successful branch deployment! I will send the preview url via email.

I was expecting a rebase instead of a merge. The history on the master and develop branch are not in sync which might cause issues when it's time to merge branch.

**Comment by chrisguindon** [comment]
Please note that unlike the master branch, we don't have any branch protection for the develop branch which means that you can --force push your branch!

**Comment by begonaalvarezd** [comment]
@chrisguindon i synced develop with master so there should be no issues when the time comes, and if so I will deal with them so no --force is needed. Thanks for all :pray: !

**Comment by chrisguindon** [comment]
@begonaalvarezd Awesome! It looks like we are good to go!

From our perspective, everything seems to be properly configured!

**Comment by chrisguindon** [comment]
Feel free to commit a simple change in the index.html file on the master branch if you wish to test the auto-deployment of the site!

**Comment by chrisguindon** [comment]
@begonaalvarezd I am just checking in! What time are you planning to push the website to make sure it's available for 7am PST?

**Comment by begonaalvarezd** [comment]
@chrisguindon I will proceed pushing to develop now so we can test, could you email me the deployment url?

**Comment by chrisguindon** [comment]
@begonaalvarezd an email has been sent!

**Comment by chrisguindon** [comment]
I think we are done here! Great job all!
