### ISSUE TITLE
Remove BiiLabs Co from Tangle EE website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/tangle.ee#17]
Please remove BiiLabs' logo from the Tangle EE website, as they are no longer a member
https://tangle.ee/members
Thank you,
Zahra

**Comment by autumnfound** [comment]
@begonaalvarezd are you able to take care of this? Thanks!

**Comment by begonaalvarezd** [comment]
@autumnfound #18 . Apologizes for the delay 🙏🏼
