### ISSUE TITLE
Missing members on staging website

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/tangle.ee#2]
@ZahraFazli  from the Eclipse foundation reported that some members are missing from the Tangle EE staging website. 

Here's the list:

1. AKITA Blockchain Solutions Pte Ltd
2. Energinet
3. STMicroelectronics International N.V.

**Comment by begonaalvarezd** [comment]
@chrisguindon is this still an open issue? AKITA, Energinet & ST are in the deployed site.

**Comment by chrisguindon** [comment]
@begonaalvarezd +1

I was only flagging this since it was reported by our membership team!
