### ISSUE TITLE
Remove Geometric Energy Corporation's logo from the Tangle EE website 

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/tangle.ee#5]
Please remove Geometric Energy Corporation's logo from the Tangle EE website 
https://tangle.ee/members. They are no longer a member of Eclipse Foundation

**Comment by ZahraFazli** [comment]
No action required. We have reinstated their membership

**Comment by chrisguindon** [comment]
Closing this issue.

//cc @begonaalvarezd
